"""empty message

Revision ID: 044ef4200a23
Revises: a45b1d6c4beb
Create Date: 2020-10-14 20:14:08.457512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044ef4200a23'
down_revision = 'a45b1d6c4beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('rows', sa.Integer(), nullable=True))
    op.add_column('areas', sa.Column('seats', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('areas', 'seats')
    op.drop_column('areas', 'rows')
    # ### end Alembic commands ###
