"""empty message

Revision ID: 08c122fd03a6
Revises: 90a934bf3f12
Create Date: 2020-10-11 21:53:13.001128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c122fd03a6'
down_revision = '90a934bf3f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subgenres', sa.Column('parentid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subgenres', 'genres', ['parentid'], ['genreid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subgenres', type_='foreignkey')
    op.drop_column('subgenres', 'parentid')
    # ### end Alembic commands ###
