"""empty message

Revision ID: 0939f5579cee
Revises: adf9cd0b494b
Create Date: 2020-10-15 16:47:28.081504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0939f5579cee'
down_revision = 'adf9cd0b494b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('seatsforshow_ticketid_fkey', 'seatsforshow', type_='foreignkey')
    op.drop_column('seatsforshow', 'ticketid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seatsforshow', sa.Column('ticketid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('seatsforshow_ticketid_fkey', 'seatsforshow', 'tickets', ['ticketid'], ['ticketid'])
    # ### end Alembic commands ###
