"""empty message

Revision ID: 0ab89880b372
Revises: 5577cde74d95
Create Date: 2020-10-09 21:18:02.551823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab89880b372'
down_revision = '5577cde74d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfomances', sa.Column('img', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfomances', 'img')
    # ### end Alembic commands ###
