"""empty message

Revision ID: 0b2263c87f52
Revises: f343545b2a08
Create Date: 2020-10-14 23:50:43.482785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2263c87f52'
down_revision = 'f343545b2a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('status', sa.Enum('free', 'close', name='seatstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seats', 'status')
    # ### end Alembic commands ###
