"""empty message

Revision ID: 0c05adaed06f
Revises: 53c63bbb6203
Create Date: 2020-10-11 23:05:11.872154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c05adaed06f'
down_revision = '53c63bbb6203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfomances', sa.Column('genreid', sa.Integer(), nullable=True))
    op.drop_constraint('perfomances_gentreid_fkey', 'perfomances', type_='foreignkey')
    op.create_foreign_key(None, 'perfomances', 'genres', ['genreid'], ['genreid'])
    op.drop_column('perfomances', 'gentreid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfomances', sa.Column('gentreid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'perfomances', type_='foreignkey')
    op.create_foreign_key('perfomances_gentreid_fkey', 'perfomances', 'genres', ['gentreid'], ['genreid'])
    op.drop_column('perfomances', 'genreid')
    # ### end Alembic commands ###
