"""empty message

Revision ID: 11d9ce5e0f60
Revises: 1b07e81bc7e8
Create Date: 2020-10-09 20:51:27.634599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d9ce5e0f60'
down_revision = '1b07e81bc7e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('actorid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('surname', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('actorid')
    )
    op.create_table('directors',
    sa.Column('dirid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('surname', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('dirid')
    )
    op.create_table('genres',
    sa.Column('genreid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('genreid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('types',
    sa.Column('typeid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('typeid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('halls',
    sa.Column('hallid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('theatreid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['theatreid'], ['theatres.theatreid'], ),
    sa.PrimaryKeyConstraint('hallid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('theatrestypes',
    sa.Column('theatreid', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['types.typeid'], ),
    sa.ForeignKeyConstraint(['theatreid'], ['theatres.theatreid'], )
    )
    op.create_table('areas',
    sa.Column('areaid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('hallid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hallid'], ['halls.hallid'], ),
    sa.PrimaryKeyConstraint('areaid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('perfomances',
    sa.Column('perfomanceid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('theatreid', sa.Integer(), nullable=True),
    sa.Column('hallid', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('duration_min', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['hallid'], ['halls.hallid'], ),
    sa.ForeignKeyConstraint(['theatreid'], ['theatres.theatreid'], ),
    sa.PrimaryKeyConstraint('perfomanceid')
    )
    op.create_table('actorsperfomances',
    sa.Column('perfomanceid', sa.Integer(), nullable=True),
    sa.Column('actorid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actorid'], ['actors.actorid'], ),
    sa.ForeignKeyConstraint(['perfomanceid'], ['perfomances.perfomanceid'], )
    )
    op.create_table('comments',
    sa.Column('commentid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('rate', sa.SmallInteger(), nullable=True),
    sa.Column('perfomanceid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['perfomanceid'], ['perfomances.perfomanceid'], ),
    sa.PrimaryKeyConstraint('commentid'),
    sa.UniqueConstraint('text')
    )
    op.create_table('directorsperfomances',
    sa.Column('perfomanceid', sa.Integer(), nullable=True),
    sa.Column('dirid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dirid'], ['directors.dirid'], ),
    sa.ForeignKeyConstraint(['perfomanceid'], ['perfomances.perfomanceid'], )
    )
    op.create_table('genresperfomances',
    sa.Column('perfomanceid', sa.Integer(), nullable=True),
    sa.Column('genreid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genreid'], ['genres.genreid'], ),
    sa.ForeignKeyConstraint(['perfomanceid'], ['perfomances.perfomanceid'], )
    )
    op.create_table('seats',
    sa.Column('seatid', sa.Integer(), nullable=False),
    sa.Column('areaid', sa.Integer(), nullable=True),
    sa.Column('row', sa.SmallInteger(), nullable=False),
    sa.Column('place', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['areaid'], ['areas.areaid'], ),
    sa.PrimaryKeyConstraint('seatid')
    )
    op.create_table('shows',
    sa.Column('showid', sa.Integer(), nullable=False),
    sa.Column('perfomanceid', sa.Integer(), nullable=True),
    sa.Column('hallid', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('one', 'two', 'three', name='status'), nullable=True),
    sa.ForeignKeyConstraint(['hallid'], ['halls.hallid'], ),
    sa.ForeignKeyConstraint(['perfomanceid'], ['perfomances.perfomanceid'], ),
    sa.PrimaryKeyConstraint('showid')
    )
    op.create_table('tickets',
    sa.Column('ticketid', sa.Integer(), nullable=False),
    sa.Column('guestname', sa.String(length=30), nullable=True),
    sa.Column('showid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['showid'], ['shows.showid'], ),
    sa.PrimaryKeyConstraint('ticketid')
    )
    op.create_unique_constraint(None, 'theatres', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'theatres', type_='unique')
    op.drop_table('tickets')
    op.drop_table('shows')
    op.drop_table('seats')
    op.drop_table('genresperfomances')
    op.drop_table('directorsperfomances')
    op.drop_table('comments')
    op.drop_table('actorsperfomances')
    op.drop_table('perfomances')
    op.drop_table('areas')
    op.drop_table('theatrestypes')
    op.drop_table('halls')
    op.drop_table('types')
    op.drop_table('genres')
    op.drop_table('directors')
    op.drop_table('actors')
    # ### end Alembic commands ###
