"""empty message

Revision ID: 13ba9775797d
Revises: 11d9ce5e0f60
Create Date: 2020-10-09 20:57:17.449607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ba9775797d'
down_revision = '11d9ce5e0f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('halls_name_key', 'halls', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('halls_name_key', 'halls', ['name'])
    # ### end Alembic commands ###
