"""empty message

Revision ID: 14e222fb2862
Revises: bfe6d74fe99c
Create Date: 2020-10-15 18:08:33.108767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e222fb2862'
down_revision = 'bfe6d74fe99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('areas', 'rows',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('areas', 'seats',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('seatsforshow', sa.Column('place', sa.Integer(), nullable=True))
    op.add_column('seatsforshow', sa.Column('row', sa.Integer(), nullable=True))
    op.add_column('seatsforshow', sa.Column('seatstatus', sa.Enum('free', 'close', name='freeclose'), nullable=True))
    op.add_column('seatsforshow', sa.Column('showid', sa.Integer(), nullable=True))
    op.add_column('seatsforshow', sa.Column('ticketid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'seatsforshow', 'tickets', ['ticketid'], ['ticketid'])
    op.create_foreign_key(None, 'seatsforshow', 'shows', ['showid'], ['showid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seatsforshow', type_='foreignkey')
    op.drop_constraint(None, 'seatsforshow', type_='foreignkey')
    op.drop_column('seatsforshow', 'ticketid')
    op.drop_column('seatsforshow', 'showid')
    op.drop_column('seatsforshow', 'seatstatus')
    op.drop_column('seatsforshow', 'row')
    op.drop_column('seatsforshow', 'place')
    op.alter_column('areas', 'seats',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('areas', 'rows',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
