"""empty message

Revision ID: 1b07e81bc7e8
Revises: 2a46f0d88d37
Create Date: 2020-10-09 01:03:06.467405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b07e81bc7e8'
down_revision = '2a46f0d88d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('theatres', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('theatres', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('theatres', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('theatres', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
