"""empty message

Revision ID: 1be67cfc1303
Revises: 51c8a08e30ed
Create Date: 2020-10-13 05:51:40.781917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be67cfc1303'
down_revision = '51c8a08e30ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'date')
    # ### end Alembic commands ###
