"""empty message

Revision ID: 2a46f0d88d37
Revises: b74885624f59
Create Date: 2020-10-09 00:46:13.279454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a46f0d88d37'
down_revision = 'b74885624f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theatres', sa.Column('img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theatres', 'img')
    # ### end Alembic commands ###
