"""empty message

Revision ID: 2ece7885644b
Revises: 62a38ac4d47c
Create Date: 2020-10-11 01:03:55.855825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ece7885644b'
down_revision = '62a38ac4d47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.drop_column('shows', 'time')
    op.drop_column('shows', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('shows', 'datetime')
    # ### end Alembic commands ###
