"""empty message

Revision ID: 51c8a08e30ed
Revises: 0c05adaed06f
Create Date: 2020-10-11 23:38:32.710595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c8a08e30ed'
down_revision = '0c05adaed06f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theatres', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theatres', 'description')
    # ### end Alembic commands ###
