"""empty message

Revision ID: 53c63bbb6203
Revises: bc24f1437e82
Create Date: 2020-10-11 22:59:51.951855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c63bbb6203'
down_revision = 'bc24f1437e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directors',
    sa.Column('directorid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('surname', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('directorid')
    )
    op.add_column('perfomances', sa.Column('directorid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'perfomances', 'directors', ['directorid'], ['directorid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'perfomances', type_='foreignkey')
    op.drop_column('perfomances', 'directorid')
    op.drop_table('directors')
    # ### end Alembic commands ###
