"""empty message

Revision ID: 5f1908e7d2cf
Revises: b1205789b1aa
Create Date: 2020-10-10 07:31:36.120439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f1908e7d2cf'
down_revision = 'b1205789b1aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theatrestypes', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theatrestypes', 'id')
    # ### end Alembic commands ###
