"""empty message

Revision ID: 62a38ac4d47c
Revises: 5f1908e7d2cf
Create Date: 2020-10-10 07:39:33.823762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a38ac4d47c'
down_revision = '5f1908e7d2cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theatrestypes',
    sa.Column('theatreid', sa.Integer(), nullable=True),
    sa.Column('typeid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['theatreid'], ['theatres.theatreid'], ),
    sa.ForeignKeyConstraint(['typeid'], ['types.typeid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theatrestypes')
    # ### end Alembic commands ###
