"""empty message

Revision ID: a45b1d6c4beb
Revises: e6c396bcee8f
Create Date: 2020-10-14 18:43:39.161974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45b1d6c4beb'
down_revision = 'e6c396bcee8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('areas_name_key', 'areas', type_='unique')
    op.drop_constraint('costs_cost_key', 'costs', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('costs_cost_key', 'costs', ['cost'])
    op.create_unique_constraint('areas_name_key', 'areas', ['name'])
    # ### end Alembic commands ###
