"""empty message

Revision ID: adf9cd0b494b
Revises: ff43436742e3
Create Date: 2020-10-15 16:45:38.514237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf9cd0b494b'
down_revision = 'ff43436742e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seatsforshow',
    sa.Column('seatsforshowid', sa.Integer(), nullable=False),
    sa.Column('areaid', sa.Integer(), nullable=True),
    sa.Column('ticketid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['areaid'], ['areas.areaid'], ),
    sa.ForeignKeyConstraint(['ticketid'], ['tickets.ticketid'], ),
    sa.PrimaryKeyConstraint('seatsforshowid')
    )
    op.drop_table('seats')
    op.add_column('tickets', sa.Column('seatid', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'seatid')
    op.create_table('seats',
    sa.Column('seatid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('areaid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('row', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('place', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('ticketid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['areaid'], ['areas.areaid'], name='seats_areaid_fkey'),
    sa.ForeignKeyConstraint(['ticketid'], ['tickets.ticketid'], name='seats_ticketid_fkey'),
    sa.PrimaryKeyConstraint('seatid', name='seats_pkey')
    )
    op.drop_table('seatsforshow')
    # ### end Alembic commands ###
