"""empty message

Revision ID: b1205789b1aa
Revises: 9bb4f7270d39
Create Date: 2020-10-10 05:16:49.963937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1205789b1aa'
down_revision = '9bb4f7270d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theatrestypes', sa.Column('typeid', sa.Integer(), nullable=True))
    op.drop_constraint('theatrestypes_tag_id_fkey', 'theatrestypes', type_='foreignkey')
    op.create_foreign_key(None, 'theatrestypes', 'types', ['typeid'], ['typeid'])
    op.drop_column('theatrestypes', 'tag_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theatrestypes', sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'theatrestypes', type_='foreignkey')
    op.create_foreign_key('theatrestypes_tag_id_fkey', 'theatrestypes', 'types', ['tag_id'], ['typeid'])
    op.drop_column('theatrestypes', 'typeid')
    # ### end Alembic commands ###
