"""empty message

Revision ID: b40bea776b79
Revises: 2ece7885644b
Create Date: 2020-10-11 21:39:33.557259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40bea776b79'
down_revision = '2ece7885644b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subgenres',
    sa.Column('subgenreid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('subgenreid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subgenresperfomances',
    sa.Column('perfomanceid', sa.Integer(), nullable=True),
    sa.Column('genreid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genreid'], ['subgenres.subgenreid'], ),
    sa.ForeignKeyConstraint(['perfomanceid'], ['perfomances.perfomanceid'], )
    )
    op.drop_table('directorsperfomances')
    op.drop_table('genresperfomances')
    op.add_column('perfomances', sa.Column('gentreid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'perfomances', 'genres', ['gentreid'], ['genreid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'perfomances', type_='foreignkey')
    op.drop_column('perfomances', 'gentreid')
    op.create_table('genresperfomances',
    sa.Column('perfomanceid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genreid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['genreid'], ['genres.genreid'], name='genresperfomances_genreid_fkey'),
    sa.ForeignKeyConstraint(['perfomanceid'], ['perfomances.perfomanceid'], name='genresperfomances_perfomanceid_fkey')
    )
    op.create_table('directorsperfomances',
    sa.Column('perfomanceid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dirid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dirid'], ['directors.dirid'], name='directorsperfomances_dirid_fkey'),
    sa.ForeignKeyConstraint(['perfomanceid'], ['perfomances.perfomanceid'], name='directorsperfomances_perfomanceid_fkey')
    )
    op.drop_table('subgenresperfomances')
    op.drop_table('subgenres')
    # ### end Alembic commands ###
