"""empty message

Revision ID: bc24f1437e82
Revises: f7fe0f8e65ec
Create Date: 2020-10-11 22:49:01.530653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc24f1437e82'
down_revision = 'f7fe0f8e65ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directors', sa.Column('directorid', sa.Integer(), nullable=False))
    op.drop_column('directors', 'dirid')
    op.add_column('perfomances', sa.Column('directorid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'perfomances', 'directors', ['directorid'], ['directorid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'perfomances', type_='foreignkey')
    op.drop_column('perfomances', 'directorid')
    op.add_column('directors', sa.Column('dirid', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('directors', 'directorid')
    # ### end Alembic commands ###
