"""empty message

Revision ID: c70c9d95235f
Revises: a8ad8ef2b336
Create Date: 2020-10-15 22:05:43.601705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70c9d95235f'
down_revision = 'a8ad8ef2b336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'seatid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('seatid', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
