"""empty message

Revision ID: d968ac02c189
Revises: 08c122fd03a6
Create Date: 2020-10-11 21:58:00.824591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd968ac02c189'
down_revision = '08c122fd03a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subgenres_name_key', 'subgenres', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('subgenres_name_key', 'subgenres', ['name'])
    # ### end Alembic commands ###
