"""empty message

Revision ID: dca8b674d3f9
Revises: 1be67cfc1303
Create Date: 2020-10-14 10:02:39.041997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca8b674d3f9'
down_revision = '1be67cfc1303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('dreated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'dreated')
    # ### end Alembic commands ###
