"""empty message

Revision ID: e6918464a3b8
Revises: 6a8da6c999bc
Create Date: 2020-10-15 19:57:17.588946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6918464a3b8'
down_revision = '6a8da6c999bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seatsforshow', sa.Column('seatstatus', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seatsforshow', 'seatstatus')
    # ### end Alembic commands ###
