"""empty message

Revision ID: e6c396bcee8f
Revises: 1d085d3eb2f7
Create Date: 2020-10-14 18:36:16.838675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c396bcee8f'
down_revision = '1d085d3eb2f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costs',
    sa.Column('costid', sa.Integer(), nullable=False),
    sa.Column('cost', sa.SmallInteger(), nullable=False),
    sa.Column('showid', sa.Integer(), nullable=True),
    sa.Column('areaid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['areaid'], ['areas.areaid'], ),
    sa.ForeignKeyConstraint(['showid'], ['shows.showid'], ),
    sa.PrimaryKeyConstraint('costid'),
    sa.UniqueConstraint('cost')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('costs')
    # ### end Alembic commands ###
