"""empty message

Revision ID: f343545b2a08
Revises: b62b6b5e8f61
Create Date: 2020-10-14 23:44:50.655604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f343545b2a08'
down_revision = 'b62b6b5e8f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('status', sa.Enum('free', 'close', name='seatstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seats', 'status')
    # ### end Alembic commands ###
