"""empty message

Revision ID: f7fe0f8e65ec
Revises: d968ac02c189
Create Date: 2020-10-11 21:59:51.460919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7fe0f8e65ec'
down_revision = 'd968ac02c189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subgenresperfomances', sa.Column('subgenreid', sa.Integer(), nullable=True))
    op.drop_constraint('subgenresperfomances_genreid_fkey', 'subgenresperfomances', type_='foreignkey')
    op.create_foreign_key(None, 'subgenresperfomances', 'subgenres', ['subgenreid'], ['subgenreid'])
    op.drop_column('subgenresperfomances', 'genreid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subgenresperfomances', sa.Column('genreid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subgenresperfomances', type_='foreignkey')
    op.create_foreign_key('subgenresperfomances_genreid_fkey', 'subgenresperfomances', 'subgenres', ['genreid'], ['subgenreid'])
    op.drop_column('subgenresperfomances', 'subgenreid')
    # ### end Alembic commands ###
