"""empty message

Revision ID: f8b55d89982f
Revises: 044ef4200a23
Create Date: 2020-10-14 23:27:45.738982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b55d89982f'
down_revision = '044ef4200a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('areaid', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('email', sa.String(length=30), nullable=True))
    op.create_foreign_key(None, 'tickets', 'areas', ['areaid'], ['areaid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'email')
    op.drop_column('tickets', 'areaid')
    # ### end Alembic commands ###
