"""empty message

Revision ID: ff43436742e3
Revises: 2f27c2ce06e4
Create Date: 2020-10-15 16:43:40.880508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff43436742e3'
down_revision = '2f27c2ce06e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seatsforshow',
    sa.Column('seatsforshowid', sa.Integer(), nullable=False),
    sa.Column('areaid', sa.Integer(), nullable=True),
    sa.Column('ticketid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['areaid'], ['areas.areaid'], ),
    sa.ForeignKeyConstraint(['ticketid'], ['tickets.ticketid'], ),
    sa.PrimaryKeyConstraint('seatsforshowid')
    )
    op.drop_table('seats')
    op.alter_column('tickets', 'seatid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('tickets_seatid_fkey', 'tickets', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('tickets_seatid_fkey', 'tickets', 'seats', ['seatid'], ['seatid'])
    op.alter_column('tickets', 'seatid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('seats',
    sa.Column('seatid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('areaid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('row', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('place', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('ticketid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['areaid'], ['areas.areaid'], name='seats_areaid_fkey'),
    sa.ForeignKeyConstraint(['ticketid'], ['tickets.ticketid'], name='seats_ticketid_fkey'),
    sa.PrimaryKeyConstraint('seatid', name='seats_pkey')
    )
    op.drop_table('seatsforshow')
    # ### end Alembic commands ###
